version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn run test
      - run: yarn run codecov -t $CI_CODECOV_TOKEN
